from snakemake.utils import min_version
min_version("8.20")

conda: workflow.source_path("envs/global.yaml")

import pandas as pd

configfile: workflow.source_path("config/config.yaml")

def get_vcf_sha256(wildcards):
    return config.get('sha256').get(wildcards.assembly).get(wildcards.chr)

include: "rules/hg19.smk"
include: "rules/hg38.smk"
# Assembly-agnostic rules
include: "rules/assembly_ag.smk"
include: "rules/wildcard_constraints.smk"
