from snakemake.utils import min_version
min_version("9.3")

conda: workflow.source_path("envs/global.yaml")

import pandas as pd

configfile: workflow.source_path("config/config.yaml")

def get_vcf_sha256(wildcards):
    return config.get('sha256').get(wildcards.assembly).get(wildcards.chr)

def script_path(script):
    return os.path.join(workflow.basedir, "scripts", script)

def env_path(env):
    return os.path.join(workflow.basedir, "envs", env)

include: "rules/wildcard_constraints.smk"
include: "rules/hg19.smk"
include: "rules/hg38.smk"
include: "rules/core.smk"
include: "rules/pruning_and_clumping.smk"
include: "rules/ldsc.smk"
